// ---------------------------------------------------------------------------
// FinSutra domain model
// Every record carries sync bookkeeping so the local DB stays the source of
// truth and Google Drive is only a backup/merge target.
// ---------------------------------------------------------------------------

export type SyncStatus = 'pending' | 'synced' | 'conflict'
export type TransactionType = 'income' | 'expense' | 'transfer'
export type PaymentMethod = 'Cash' | 'Bank' | 'UPI' | 'Card' | 'Cheque' | 'Other'
export type InvoiceStatus =
  | 'draft'
  | 'sent'
  | 'partially_paid'
  | 'paid'
  | 'overdue'
export type BusinessType =
  | 'Freelancer'
  | 'Agency'
  | 'Consulting'
  | 'Services'
  | 'Retail'
  | 'Trading'
  | 'Other'

export type DataMode = 'local' | 'drive'

export interface Company {
  id: string
  name: string
  owner_name: string
  email: string
  phone: string
  currency: string
  financial_year: string
  business_type: BusinessType
  gstin?: string
  logo?: string
  address?: string
  data_mode: DataMode
  created_at: string
  updated_at: string
}

export interface User {
  id: string
  company_id: string
  name: string
  email: string
  role: string
  created_at: string
}

export interface Customer {
  id: string
  company_id: string
  name: string
  email?: string
  phone?: string
  address?: string
  gstin?: string
  notes?: string
  created_at: string
  updated_at: string
  deleted_at?: string | null
  sync_status: SyncStatus
}

export interface Vendor {
  id: string
  company_id: string
  name: string
  email?: string
  phone?: string
  address?: string
  gstin?: string
  notes?: string
  created_at: string
  updated_at: string
  deleted_at?: string | null
  sync_status: SyncStatus
}

export interface Transaction {
  id: string
  company_id: string
  type: TransactionType
  amount: number
  currency: string
  date: string // ISO date (yyyy-MM-dd)
  description: string
  category: string
  customer_id?: string | null
  vendor_id?: string | null
  payment_method: PaymentMethod
  status: 'completed' | 'pending'
  reference_number?: string
  notes?: string
  attachment_ids: string[]
  // transfer-specific
  transfer_to?: string
  // link to a payment record (when this txn was generated by a payment)
  payment_id?: string | null
  created_at: string
  updated_at: string
  deleted_at?: string | null
  created_by?: string
  device_id: string
  sync_status: SyncStatus
}

export interface InvoiceItem {
  id: string
  invoice_id: string
  description: string
  quantity: number
  unit_price: number
  tax_rate: number // percent
  discount: number // percent
  line_total: number
}

export interface Invoice {
  id: string
  company_id: string
  invoice_number: string
  customer_id: string
  issue_date: string
  due_date: string
  subtotal: number
  tax: number
  discount: number
  total: number
  paid_amount: number
  outstanding_amount: number
  status: InvoiceStatus
  notes?: string
  payment_instructions?: string
  attachment_ids?: string[]
  created_at: string
  updated_at: string
  deleted_at?: string | null
  device_id: string
  sync_status: SyncStatus
}

export interface Payment {
  id: string
  company_id: string
  invoice_id?: string | null
  customer_id?: string | null
  vendor_id?: string | null
  amount: number
  date: string
  payment_method: PaymentMethod
  reference_number?: string
  notes?: string
  direction: 'in' | 'out' // in = we received, out = we paid
  attachment_ids?: string[]
  created_at: string
  updated_at: string
  device_id: string
  sync_status: SyncStatus
}

export type DocumentCategory =
  | 'Invoices'
  | 'Receipts'
  | 'Bills'
  | 'Payment Evidence'
  | 'Other'

export interface DocumentRecord {
  id: string
  company_id: string
  filename: string
  mime_type: string
  size: number
  category: DocumentCategory
  blob?: Blob // stored locally in IndexedDB
  drive_path?: string
  linked_transaction_id?: string | null
  linked_invoice_id?: string | null
  linked_customer_id?: string | null
  linked_vendor_id?: string | null
  created_at: string
  updated_at: string
  sync_status: SyncStatus
}

export interface Category {
  id: string
  company_id: string
  name: string
  type: 'income' | 'expense'
  created_at: string
}

export type SyncOperation = 'CREATE' | 'UPDATE' | 'DELETE'

export interface SyncEvent {
  id: string
  entity_type: string
  entity_id: string
  operation: SyncOperation
  payload: string // JSON snapshot
  timestamp: string
  device_id: string
  sync_status: SyncStatus
}

export interface SyncMetadata {
  device_id: string // primary key (single row uses a fixed key)
  last_sync_at?: string
  drive_folder_id?: string
  drive_email?: string
  sync_version: number
  connected: boolean
  demo_mode: boolean
}

export interface AppNotification {
  id: string
  company_id: string
  type: 'overdue' | 'due_soon' | 'payable_due' | 'sync_failure' | 'info'
  title: string
  body: string
  link?: string
  read: boolean
  created_at: string
}
